### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by palaster** [palaster/BloodBank#10]
- [ ] Re-name the Mod to something else.
- [ ] Clean-up NBT usage.
- [ ] Consolidate all fragmented code.
- [ ] Use WeakReferences.
- [ ] Re-organize features.
- [ ] Balance Features.
- [ ] Use Java annotations (@Nullable, @NotNull).
- [ ] Clean-up language files.

I will complete this when I can be bothered to do so.
